version: "3.1"

services:

  traefik:
    image: quay.io/alex_blazh/trivago-the-devops-challenge-traefik:1.7.9-alpine
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --docker
      - --docker.swarmMode
      - --docker.domain="trivago.com"
      - --docker.watch 
      - --api
      - --logLevel=DEBUG
      # - --docker.constraints="tag==web"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"

  web-app:
    image: quay.io/alex_blazh/trivago-the-devops-challenge-web-app
    ports:
      - 8081:80
    networks:
      - internal
      - public
    deploy:
      restart_policy:
        condition: any
      replicas: 3
      labels:
      # - "traefik.tags=web-app"
      - "traefik.port=80"
      - "traefik.protocol=http"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.backend=web-app"
      # - "traefik.frontend.rule=Host:web-app.trivago.com"
      - "traefik.frontend.rule=PathPrefix:/"
      - "backend.LoadBalancer.Stickiness=true"
      - "traefik.backend.loadbalancer.swarm=true"
    depends_on:
      - db
    environment:
      DB_URL: postgresql://db:5432/trivago

  db:
    image: quay.io/alex_blazh/trivago-the-devops-challenge-postgres:10.7-alpine
    volumes:
      - /mnt/data/pgdata:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      # POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
      POSTGRES_PASSWORD: SUPER_SECRET_PASSWORD
      POSTGRES_USER: trivago
      POSTGRES_DB: trivago
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - "node.labels.type == databases"
      labels:
        - "traefik.enable=false"

networks:
  public:
    driver: overlay
    external: true
  internal:
    driver: overlay
    external: true