FROM docker.elastic.co/elasticsearch/elasticsearch:6.6.1

LABEL Author="Oleg Blazhyievskyi <Oleg.Blazhyievskyi@gmail.com>"

# COPY --chown=elasticsearch:elasticsearch elasticsearch.yml /usr/share/elasticsearch/config/

